---
title: '`Course Project` Regression Models'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: 'Anderson H Uyekita'
  course: 'Regression Models'
  course_url: 'https://www.coursera.org/learn/regression-models'
  specialization: 'Data Science: Statistics and Machine Learning Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-statistics-machine-learning'
  instructor: 'Brian Caffo'
  course_start: !r lubridate::ymd('2022/07/05', tz = 'America/Sao_Paulo')
  course_finish: !r lubridate::ymd('2022/07/09', tz = 'America/Sao_Paulo')
  week: "Week 4"
  slug: 'Week%204'
  rpubs: 'https://rpubs.com/AndersonUyekita/regression-models_reproducible-research'
  project_repo: 'https://github.com/AndersonUyekita/regression-models_course-project'
  codebook: 'https://github.com/AndersonUyekita/regression-models_course-project/blob/master/codebook.md'
  instructions: 'https://github.com/AndersonUyekita/regression-models_course-project/blob/master/instructions.md'
always_allow_html: true
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
library(lubridate)
library(ggplot2)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F4C4; README: [README.md](%s)", "./README.md")}else{sprintf(fmt = "* &#x1F4C4; README: [README.md](%s){target='_blank' rel='noopener'}", params$project_repo)}`
`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1F30E; Rpubs: [Interactive Document](%s)", params$rpubs)}else{sprintf(fmt = "* &#x1F4E6; Github Repository: [Static Document](%s){target='_blank' rel='noopener'}", params$project_repo)}`

------------------------------------------------------------------------

## Instructions

### 1. Introduction

You work for _Motor Trend_, a magazine about the automobile industry. Looking at a data set of a collection of cars, they are interested in exploring the relationship between a set of variables and miles per gallon (MPG) (outcome). They are particularly interested in the following two questions:

* “Is an automatic or manual transmission better for MPG”
* "Quantify the MPG difference between automatic and manual transmissions"


### 2. Question

Take the `mtcars` data set and write up an analysis to answer their question using regression models and exploratory data analyses.

Your report must be:

* Written as a PDF printout of a compiled (using knitr) R markdown document.
* Brief. Roughly the equivalent of 2 pages or less for the main text. Supporting figures in an appendix can be included up to 5 total pages including the 2 for the main report. The appendix can only include figures.
* Include a first paragraph executive summary.

Upload your PDF by clicking the Upload button below the text box.

### 3. Review Criteria

#### 3.1. Peer Grading

* The criteria that your classmates will use to evaluate and grade your work are shown below.
* Each criteria is binary: (1 point = criteria met acceptably; 0 points = criteria not met acceptably)
* Your Course Project score will be the sum of the points and will count as 40% of your final grade in the course. 

#### 3.2. Criteria

* Did the student interpret the coefficients correctly?
* Did the student do some exploratory data analyses?
* Did the student fit multiple models and detail their strategy for model selection?
* Did the student answer the questions of interest or detail why the question(s) is (are) not answerable?
* Did the student do a residual plot and some diagnostics?
* Did the student quantify the uncertainty in their conclusions and/or perform an inference correctly?
* Was the report brief (about 2 pages long) for the main body of the report and no longer than 5 with supporting appendix of figures?
* Did the report include an executive summary?
* Was the report done in Rmd (knitr)?